/**
 * Event shapes and the category list, without the database.
 *
 * The admin editor and the public submission form are both client
 * components and need EVENT_CATEGORIES to build their dropdowns.
 * Importing a value out of events.ts would drag "server-only" across
 * the boundary and fail the build.
 */

export type EventCategory =
  | "festival"
  | "market"
  | "concert"
  | "family"
  | "food"
  | "grand_opening"
  | "charity"
  | "community";

export type EventStatus = "pending" | "published" | "rejected" | "archived";

/** Straight from the roadmap's What's Happening list. */
export const EVENT_CATEGORIES: {
  value: EventCategory;
  label: string;
}[] = [
  { value: "festival", label: "Festival" },
  { value: "market", label: "Market" },
  { value: "concert", label: "Live music" },
  { value: "family", label: "Family" },
  { value: "food", label: "Food and drink" },
  { value: "grand_opening", label: "Grand opening" },
  { value: "charity", label: "Charity" },
  { value: "community", label: "Community" },
];

export const categoryLabel = (c: EventCategory) =>
  EVENT_CATEGORIES.find((x) => x.value === c)?.label ?? "Community";

/** Where the listing came from, which decides whether it needs reading. */
export type EventSource = "staff" | "submitted" | "imported";

export type LocalEvent = {
  id: number;
  slug: string;
  title: string;
  summary: string;
  bodyHtml: string;
  heroMediaId: number | null;
  /** ISO. Always set; an event with no start is not an event. */
  startsAt: string;
  /** ISO, or empty for something that finishes when it finishes. */
  endsAt: string;
  allDay: boolean;
  venueName: string;
  address: string;
  placeSlug: string;
  businessId: number | null;
  /** Filled in on read, for the byline. */
  businessName?: string;
  businessSlug?: string;
  category: EventCategory;
  url: string;
  ticketUrl: string;
  priceText: string;
  status: EventStatus;
  featured: boolean;
  source: EventSource;
  submittedEmail: string;
  /**
   * Ties the instances of a repeating thing together.
   *
   * There are deliberately no recurrence rules. A weekly farmers market
   * is a real row per week with a shared series id, generated by a
   * button, so cancelling one week or moving one week is an ordinary
   * edit rather than an exception buried in a rule. Recurrence engines
   * are where calendar projects go to die.
   */
  seriesId: number | null;
  /**
   * Where an imported event came from, empty for everything typed in.
   *
   * The provider and their identifier together are what an importer
   * would match on to decide between an update and an insert; the URL
   * is the page it was read from, for checking a detail against the
   * source later. Nothing writes these yet.
   */
  externalSource?: string;
  externalId?: string;
  sourceUrl?: string;
  /** Pretty forms, worked out once on read. */
  dayLabel?: string;
  timeLabel?: string;
  monthLabel?: string;
  dayOfMonth?: string;
  /**
   * The other end, for anything that does not finish the day it starts.
   *
   * A three-day festival showing only its opening date reads as a
   * one-day event, which is the single most common way a calendar
   * misleads somebody into turning up on the wrong day.
   */
  endDayLabel?: string;
  endTimeLabel?: string;
  multiDay?: boolean;
};

/**
 * The clock the Lowcountry actually runs on.
 *
 * Servers run in UTC, and a date formatted without a zone is formatted
 * in theirs. That is invisible for most of the day and wrong every
 * evening: an 8pm Friday concert becomes midnight Saturday, which puts
 * it under the wrong heading, on the wrong card, and sends somebody out
 * a day late. Every label built from an event's time passes this.
 */
export const SITE_TZ = "America/New_York";

/**
 * Puts a dollar sign in front of an amount that has not got one.
 *
 * People type "10" or "20 adults, 10 kids" into a price box, and a
 * calendar full of bare numbers reads as a mistake. Done on display
 * rather than on save so the stored text stays exactly what was typed
 * and can be corrected without a migration.
 *
 * Two things are deliberately left alone. An amount already carrying a
 * sign is never touched, and a number that is plainly an age or a
 * percentage — "18+", "21 and over" — is not money. Everything else is
 * assumed to be a price, because it is a price field.
 *
 * No lookbehind: Safari only learned it in 16.4, and an unsupported
 * regex literal is a parse error that takes the whole bundle with it,
 * not a quiet failure on one line.
 */
export function formatPrice(raw: string): string {
  const s = String(raw ?? "").trim();
  if (!s) return "";
  if (/^(?:free|no charge|free admission|free entry|\$?0(?:\.00)?)$/i.test(s)) {
    return "Free";
  }
  return s.replace(
    /(^|[^$\d.])(\d{1,4}(?:\.\d{2})?)/g,
    (match, before: string, amount: string, offset: number, whole: string) => {
      const after = whole.slice(offset + match.length);
      if (/^(?:\+|%|\s*(?:and|&)\s*(?:over|up|older)\b)/i.test(after)) {
        return match;
      }
      return `${before}$${amount}`;
    },
  );
}

/**
 * The lowest number in a price, for schema.org `offers`.
 *
 * Google wants a numeric price to show a range in an event result, and
 * "from" is the honest reading of the first figure in "$10 in advance,
 * $15 on the door". Anything with no figure at all is left out rather
 * than guessed at; an event marked up as costing 0 when it does not is
 * worse than one with no offer at all.
 */
export function priceNumber(raw: string): number | undefined {
  const s = String(raw ?? "").trim();
  if (!s) return undefined;
  if (/^(?:free|no charge|free admission|free entry)/i.test(s)) return 0;
  const m = s.match(/(\d{1,5}(?:\.\d{1,2})?)/);
  if (!m) return undefined;
  const n = Number(m[1]);
  return Number.isFinite(n) ? n : undefined;
}

export const slugifyEvent = (s: string) =>
  s
    .toLowerCase()
    .trim()
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 160);
