/**
 * Event shapes and the category list, without the database.
 *
 * The admin editor and the public submission form are both client
 * components and need EVENT_CATEGORIES to build their dropdowns.
 * Importing a value out of events.ts would drag "server-only" across
 * the boundary and fail the build.
 */

export type EventCategory =
  | "festival"
  | "market"
  | "concert"
  | "family"
  | "food"
  | "grand_opening"
  | "charity"
  | "community";

export type EventStatus = "pending" | "published" | "rejected" | "archived";

/** Straight from the roadmap's What's Happening list. */
export const EVENT_CATEGORIES: {
  value: EventCategory;
  label: string;
}[] = [
  { value: "festival", label: "Festival" },
  { value: "market", label: "Market" },
  { value: "concert", label: "Live music" },
  { value: "family", label: "Family" },
  { value: "food", label: "Food and drink" },
  { value: "grand_opening", label: "Grand opening" },
  { value: "charity", label: "Charity" },
  { value: "community", label: "Community" },
];

export const categoryLabel = (c: EventCategory) =>
  EVENT_CATEGORIES.find((x) => x.value === c)?.label ?? "Community";

/** Where the listing came from, which decides whether it needs reading. */
export type EventSource = "staff" | "submitted" | "imported";

export type LocalEvent = {
  id: number;
  slug: string;
  title: string;
  summary: string;
  bodyHtml: string;
  heroMediaId: number | null;
  /** ISO. Always set; an event with no start is not an event. */
  startsAt: string;
  /** ISO, or empty for something that finishes when it finishes. */
  endsAt: string;
  allDay: boolean;
  venueName: string;
  address: string;
  placeSlug: string;
  businessId: number | null;
  /** Filled in on read, for the byline. */
  businessName?: string;
  businessSlug?: string;
  category: EventCategory;
  url: string;
  ticketUrl: string;
  priceText: string;
  status: EventStatus;
  featured: boolean;
  source: EventSource;
  submittedEmail: string;
  /**
   * Ties the instances of a repeating thing together.
   *
   * There are deliberately no recurrence rules. A weekly farmers market
   * is a real row per week with a shared series id, generated by a
   * button, so cancelling one week or moving one week is an ordinary
   * edit rather than an exception buried in a rule. Recurrence engines
   * are where calendar projects go to die.
   */
  seriesId: number | null;
  /** Pretty forms, worked out once on read. */
  dayLabel?: string;
  timeLabel?: string;
  monthLabel?: string;
  dayOfMonth?: string;
};

export const slugifyEvent = (s: string) =>
  s
    .toLowerCase()
    .trim()
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
    .slice(0, 160);
