import "server-only";
import { sql } from "drizzle-orm";
import { cleanStoryHtml } from "@/lib/stories";
import {
  slugifyEvent,
  type EventCategory,
  type EventSource,
  type EventStatus,
  type LocalEvent,
} from "@/lib/events-types";

/**
 * What's Happening.
 *
 * The second reason for a resident to come back, and the half of the
 * roadmap that gives the directory something to sit beside. An event
 * belongs to a place and often to a business, which is what puts it on
 * that business's listing without anybody linking it twice.
 *
 * Two decisions worth stating. There are no recurrence rules: a weekly
 * market is a real row per week sharing a series id, generated by a
 * button, so moving or cancelling one week is an ordinary edit rather
 * than an exception buried inside a rule. And anybody can submit one,
 * because a calendar only Andrew can fill is a weekly chore with no end
 * date, and that is how local event calendars quietly die around month
 * four.
 */

export type { LocalEvent, EventCategory, EventStatus } from "@/lib/events-types";
export {
  EVENT_CATEGORIES,
  categoryLabel,
  slugifyEvent,
} from "@/lib/events-types";

const CATEGORIES = new Set<string>([
  "festival",
  "market",
  "concert",
  "family",
  "food",
  "grand_opening",
  "charity",
  "community",
]);
const STATUSES = new Set<string>([
  "pending",
  "published",
  "rejected",
  "archived",
]);

let ready = false;

/**
 * Created on write, including the public submission.
 *
 * That is the one public path allowed to run DDL here, for the same
 * reason the unsubscribe table is: the alternative is that the very
 * first person to submit an event gets an error, and a submission form
 * that fails on its first use never gets a second.
 */
async function ensureTable() {
  if (ready) return;
  const { db } = await import("@/lib/db");
  await db.execute(
    sql`CREATE TABLE IF NOT EXISTS lbs_events (
      id INT AUTO_INCREMENT PRIMARY KEY,
      slug VARCHAR(180) NOT NULL UNIQUE,
      title VARCHAR(300) NOT NULL,
      summary TEXT NULL,
      body_html MEDIUMTEXT NULL,
      hero_media_id INT NULL,
      starts_at DATETIME NOT NULL,
      ends_at DATETIME NULL,
      all_day TINYINT NOT NULL DEFAULT 0,
      venue_name VARCHAR(200) NULL,
      address VARCHAR(300) NULL,
      place_slug VARCHAR(80) NULL,
      business_id INT NULL,
      category VARCHAR(24) NOT NULL DEFAULT 'community',
      url VARCHAR(500) NULL,
      ticket_url VARCHAR(500) NULL,
      price_text VARCHAR(120) NULL,
      status VARCHAR(16) NOT NULL DEFAULT 'pending',
      featured TINYINT NOT NULL DEFAULT 0,
      source VARCHAR(16) NOT NULL DEFAULT 'staff',
      submitted_email VARCHAR(191) NULL,
      series_id INT NULL,
      external_source VARCHAR(40) NULL,
      external_id VARCHAR(191) NULL,
      source_url VARCHAR(500) NULL,
      created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      KEY when_idx (status, starts_at),
      KEY place_idx (place_slug),
      KEY series_idx (series_id),
      UNIQUE KEY external_ref (external_source, external_id)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`,
  );

  /**
   * Room for a feed, before there is one.
   *
   * Nothing writes these yet. They exist because the expensive half of
   * ingesting somebody else's calendar is not the fetching, it is
   * knowing whether you already have the row — and that has to be
   * decided against an identifier the other side controls, not against
   * a title, which they will edit. Retrofitting the key after a few
   * thousand rows have landed means reconciling duplicates by hand.
   *
   * The provider is stored beside the identifier because two feeds will
   * eventually both hand over an id of "1042". `source_url` is where we
   * got it from, which is a different thing from `url`: that one is the
   * event's own page, and is what a reader is sent to.
   *
   * MySQL lets a unique index hold any number of rows whose columns are
   * both NULL, so everything typed in by hand is unaffected.
   */
  for (const stmt of [
    sql`ALTER TABLE lbs_events
        ADD COLUMN external_source VARCHAR(40) NULL,
        ADD COLUMN external_id VARCHAR(191) NULL,
        ADD COLUMN source_url VARCHAR(500) NULL`,
    sql`ALTER TABLE lbs_events
        ADD UNIQUE KEY external_ref (external_source, external_id)`,
  ]) {
    // Tolerated rather than checked, as elsewhere: the only reason
    // either fails is that it has already been applied, and the
    // submission form must not start erroring over a column it has.
    try {
      await db.execute(stmt);
    } catch {
      /* already there */
    }
  }
  ready = true;
}

type Row = {
  id: number;
  slug: string;
  title: string;
  summary: string | null;
  body_html: string | null;
  hero_media_id: number | null;
  starts_at: unknown;
  ends_at: unknown;
  all_day: number | null;
  venue_name: string | null;
  address: string | null;
  place_slug: string | null;
  business_id: number | null;
  business_name?: string | null;
  business_slug?: string | null;
  category: string;
  url: string | null;
  ticket_url: string | null;
  price_text: string | null;
  status: string;
  featured: number | null;
  source: string;
  submitted_email: string | null;
  series_id: number | null;
  // Optional because the public reads never run the ALTER above, so a
  // database that has not had a write since this shipped answers
  // SELECT e.* without them.
  external_source?: string | null;
  external_id?: string | null;
  source_url?: string | null;
};

const asDate = (d: unknown) => {
  const dt = d instanceof Date ? d : new Date(String(d ?? ""));
  return isNaN(dt.getTime()) ? undefined : dt;
};

const iso = (d: unknown) => asDate(d)?.toISOString() ?? "";

const toEvent = (r: Row): LocalEvent => {
  const start = asDate(r.starts_at);
  const end = asDate(r.ends_at);
  const allDay = Number(r.all_day) === 1;
  // Compared by calendar day rather than by elapsed hours, so a thing
  // running 8pm to 1am is one night out and not a two-day event.
  const multiDay =
    !!start && !!end && start.toDateString() !== end.toDateString();
  return {
    id: Number(r.id),
    slug: String(r.slug),
    title: String(r.title ?? ""),
    summary: r.summary ?? "",
    bodyHtml: r.body_html ?? "",
    heroMediaId: r.hero_media_id ?? null,
    startsAt: iso(r.starts_at),
    endsAt: iso(r.ends_at),
    allDay,
    venueName: r.venue_name ?? "",
    address: r.address ?? "",
    placeSlug: r.place_slug ?? "",
    businessId: r.business_id ?? null,
    businessName: r.business_name ?? undefined,
    businessSlug: r.business_slug ?? undefined,
    category: (CATEGORIES.has(r.category)
      ? r.category
      : "community") as EventCategory,
    url: r.url ?? "",
    ticketUrl: r.ticket_url ?? "",
    priceText: r.price_text ?? "",
    status: (STATUSES.has(r.status) ? r.status : "pending") as EventStatus,
    featured: Number(r.featured) === 1,
    source: (r.source === "submitted" || r.source === "imported"
      ? r.source
      : "staff") as EventSource,
    submittedEmail: r.submitted_email ?? "",
    seriesId: r.series_id ?? null,
    externalSource: r.external_source ?? "",
    externalId: r.external_id ?? "",
    sourceUrl: r.source_url ?? "",
    dayLabel: start?.toLocaleDateString("en-US", {
      weekday: "long",
      month: "long",
      day: "numeric",
    }),
    monthLabel: start?.toLocaleDateString("en-US", { month: "short" }),
    dayOfMonth: start ? String(start.getDate()) : undefined,
    // An all-day thing has no useful clock time, and printing 12:00 AM
    // beside it reads as a mistake rather than as "all day".
    timeLabel: allDay
      ? "All day"
      : start?.toLocaleTimeString("en-US", {
          hour: "numeric",
          minute: "2-digit",
        }),
    multiDay,
    endDayLabel: end?.toLocaleDateString("en-US", {
      weekday: "long",
      month: "long",
      day: "numeric",
    }),
    endTimeLabel: allDay
      ? undefined
      : end?.toLocaleTimeString("en-US", {
          hour: "numeric",
          minute: "2-digit",
        }),
  };
};

const SELECT = sql`SELECT e.*, b.business_name, b.slug AS business_slug
                     FROM lbs_events e
                     LEFT JOIN directory_businesses b ON b.id = e.business_id`;

/* ---------- reads ---------- */

export type EventQuery = {
  category?: EventCategory;
  placeSlug?: string;
  businessId?: number;
  limit?: number;
  offset?: number;
  /** Include events that have already happened. */
  includePast?: boolean;
};

/**
 * Upcoming, published, soonest first.
 *
 * "Upcoming" is judged against the end where there is one, so a
 * three-day festival stays on the calendar on its second day rather
 * than vanishing the morning after it opened.
 */
export async function publishedEvents(q: EventQuery = {}): Promise<LocalEvent[]> {
  const limit = Math.min(Math.max(q.limit ?? 24, 1), 100);
  const offset = Math.max(q.offset ?? 0, 0);
  try {
    const { db } = await import("@/lib/db");
    const where = [sql`e.status = 'published'`];
    if (!q.includePast) {
      where.push(sql`COALESCE(e.ends_at, e.starts_at) >= NOW()`);
    }
    if (q.category) where.push(sql`e.category = ${q.category}`);
    if (q.placeSlug) where.push(sql`e.place_slug = ${q.placeSlug}`);
    if (q.businessId) where.push(sql`e.business_id = ${q.businessId}`);
    const rows = (await db.execute(
      sql`${SELECT} WHERE ${sql.join(where, sql` AND `)}
           ORDER BY e.starts_at ${q.includePast ? sql`DESC` : sql`ASC`}
           LIMIT ${limit} OFFSET ${offset}`,
    )) as unknown as [Row[]];
    return (rows[0] ?? []).map(toEvent);
  } catch (e) {
    console.error("[events] list failed:", e);
    return [];
  }
}

export async function countPublishedEvents(q: EventQuery = {}): Promise<number> {
  try {
    const { db } = await import("@/lib/db");
    const where = [sql`status = 'published'`];
    if (!q.includePast) {
      where.push(sql`COALESCE(ends_at, starts_at) >= NOW()`);
    }
    if (q.category) where.push(sql`category = ${q.category}`);
    if (q.placeSlug) where.push(sql`place_slug = ${q.placeSlug}`);
    const rows = (await db.execute(
      sql`SELECT COUNT(*) AS n FROM lbs_events WHERE ${sql.join(where, sql` AND `)}`,
    )) as unknown as [{ n: number | string }[]];
    return Number(rows[0]?.[0]?.n ?? 0);
  } catch {
    return 0;
  }
}

export async function getPublishedEvent(
  slug: string,
): Promise<LocalEvent | undefined> {
  try {
    const { db } = await import("@/lib/db");
    const rows = (await db.execute(
      sql`${SELECT} WHERE e.slug = ${slug} AND e.status = 'published' LIMIT 1`,
    )) as unknown as [Row[]];
    const r = rows[0]?.[0];
    return r ? toEvent(r) : undefined;
  } catch (e) {
    console.error("[events] read failed:", e);
    return undefined;
  }
}

/** Everything, for the admin. Pending first: those are the job. */
export async function listEvents(limit = 200): Promise<LocalEvent[]> {
  try {
    const { db } = await import("@/lib/db");
    const rows = (await db.execute(
      sql`${SELECT}
           ORDER BY (e.status = 'pending') DESC, e.starts_at ASC
           LIMIT ${limit}`,
    )) as unknown as [Row[]];
    return (rows[0] ?? []).map(toEvent);
  } catch (e) {
    console.error("[events] admin list failed:", e);
    return [];
  }
}

export async function getEvent(id: number): Promise<LocalEvent | undefined> {
  try {
    const { db } = await import("@/lib/db");
    const rows = (await db.execute(
      sql`${SELECT} WHERE e.id = ${id} LIMIT 1`,
    )) as unknown as [Row[]];
    const r = rows[0]?.[0];
    return r ? toEvent(r) : undefined;
  } catch (e) {
    console.error("[events] read failed:", e);
    return undefined;
  }
}

/** How many are waiting to be read, for the admin badge. */
export async function countPendingEvents(): Promise<number> {
  try {
    const { db } = await import("@/lib/db");
    const rows = (await db.execute(
      sql`SELECT COUNT(*) AS n FROM lbs_events WHERE status = 'pending'`,
    )) as unknown as [{ n: number | string }[]];
    return Number(rows[0]?.[0]?.n ?? 0);
  } catch {
    return 0;
  }
}

/* ---------- writes ---------- */

export type EventPatch = {
  title: string;
  summary: string;
  bodyHtml: string;
  heroMediaId: number | null;
  startsAt: string;
  endsAt: string;
  allDay: boolean;
  venueName: string;
  address: string;
  placeSlug: string;
  businessId: number | null;
  category: EventCategory;
  url: string;
  ticketUrl: string;
  priceText: string;
  status: EventStatus;
  featured: boolean;
  source?: EventSource;
  submittedEmail?: string;
};

export type EventResult =
  | { ok: true; id: number; slug: string }
  | { ok: false; error: string };

async function freeSlug(base: string, exceptId: number | null): Promise<string> {
  const { db } = await import("@/lib/db");
  const root = base || "event";
  for (let n = 0; n < 60; n += 1) {
    const candidate = n === 0 ? root : `${root}-${n + 1}`;
    const rows = (await db.execute(
      sql`SELECT id FROM lbs_events WHERE slug = ${candidate} LIMIT 1`,
    )) as unknown as [{ id: number }[]];
    const found = rows[0]?.[0];
    if (!found || (exceptId !== null && Number(found.id) === exceptId)) {
      return candidate;
    }
  }
  return `${root}-${Date.now()}`;
}

/**
 * A slug that carries the date.
 *
 * A weekly market would otherwise produce "summerville-farmers-market",
 * then "-2", then "-3", and nobody could tell which week a link pointed
 * at. The date makes every instance of a series readable on its own.
 */
const slugFor = (title: string, startsAt: string) => {
  const d = asDate(startsAt);
  const stamp = d
    ? `-${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(
        d.getDate(),
      ).padStart(2, "0")}`
    : "";
  return `${slugifyEvent(title)}${stamp}`;
};

export async function saveEvent(
  id: number | null,
  patch: EventPatch,
): Promise<EventResult> {
  const title = patch.title.trim();
  if (title.length < 3) return { ok: false, error: "Give the event a name." };
  const start = asDate(patch.startsAt);
  if (!start) return { ok: false, error: "When does it start?" };
  const end = asDate(patch.endsAt);
  if (end && end < start) {
    return { ok: false, error: "It cannot end before it starts." };
  }

  try {
    await ensureTable();
    const { db } = await import("@/lib/db");
    const body = cleanStoryHtml(patch.bodyHtml ?? "");
    const category = CATEGORIES.has(patch.category)
      ? patch.category
      : "community";
    const status = STATUSES.has(patch.status) ? patch.status : "pending";

    if (id) {
      // The slug stops following the name once it is live, the same rule
      // stories follow: a published event's address may be in a
      // newsletter already.
      const cur = (await db.execute(
        sql`SELECT slug, status FROM lbs_events WHERE id = ${id} LIMIT 1`,
      )) as unknown as [{ slug: string; status: string }[]];
      const row = cur[0]?.[0];
      if (!row) return { ok: false, error: "That event is not here any more." };
      const finalSlug =
        row.status === "published"
          ? String(row.slug)
          : await freeSlug(slugFor(title, patch.startsAt), id);

      await db.execute(
        sql`UPDATE lbs_events
               SET slug = ${finalSlug}, title = ${title},
                   summary = ${patch.summary ?? ""}, body_html = ${body},
                   hero_media_id = ${patch.heroMediaId},
                   starts_at = ${start}, ends_at = ${end ?? null},
                   all_day = ${patch.allDay ? 1 : 0},
                   venue_name = ${patch.venueName ?? ""},
                   address = ${patch.address ?? ""},
                   place_slug = ${patch.placeSlug || null},
                   business_id = ${patch.businessId},
                   category = ${category}, url = ${patch.url ?? ""},
                   ticket_url = ${patch.ticketUrl ?? ""},
                   price_text = ${patch.priceText ?? ""},
                   status = ${status}, featured = ${patch.featured ? 1 : 0}
             WHERE id = ${id}`,
      );
      return { ok: true, id, slug: finalSlug };
    }

    const slug = await freeSlug(slugFor(title, patch.startsAt), null);
    await db.execute(
      sql`INSERT INTO lbs_events
            (slug, title, summary, body_html, hero_media_id, starts_at,
             ends_at, all_day, venue_name, address, place_slug, business_id,
             category, url, ticket_url, price_text, status, featured,
             source, submitted_email)
          VALUES (${slug}, ${title}, ${patch.summary ?? ""}, ${body},
                  ${patch.heroMediaId}, ${start}, ${end ?? null},
                  ${patch.allDay ? 1 : 0}, ${patch.venueName ?? ""},
                  ${patch.address ?? ""}, ${patch.placeSlug || null},
                  ${patch.businessId}, ${category}, ${patch.url ?? ""},
                  ${patch.ticketUrl ?? ""}, ${patch.priceText ?? ""},
                  ${status}, ${patch.featured ? 1 : 0},
                  ${patch.source ?? "staff"}, ${patch.submittedEmail ?? ""})`,
    );
    const back = (await db.execute(
      sql`SELECT id FROM lbs_events WHERE slug = ${slug} LIMIT 1`,
    )) as unknown as [{ id: number }[]];
    const newId = Number(back[0]?.[0]?.id ?? 0);
    if (!newId) return { ok: false, error: "That saved but could not be read back." };
    return { ok: true, id: newId, slug };
  } catch (e) {
    console.error("[events] save failed:", e);
    return { ok: false, error: "That did not save." };
  }
}

export async function setEventStatus(
  id: number,
  status: EventStatus,
): Promise<{ ok: true } | { ok: false; error: string }> {
  if (!STATUSES.has(status)) return { ok: false, error: "Unknown status." };
  try {
    await ensureTable();
    const { db } = await import("@/lib/db");
    await db.execute(
      sql`UPDATE lbs_events SET status = ${status} WHERE id = ${id}`,
    );
    return { ok: true };
  } catch (e) {
    console.error("[events] status failed:", e);
    return { ok: false, error: "That did not save." };
  }
}

export async function deleteEvent(
  id: number,
): Promise<{ ok: true } | { ok: false; error: string }> {
  try {
    await ensureTable();
    const { db } = await import("@/lib/db");
    await db.execute(sql`DELETE FROM lbs_events WHERE id = ${id}`);
    return { ok: true };
  } catch (e) {
    console.error("[events] delete failed:", e);
    return { ok: false, error: "That did not delete." };
  }
}

/** A ceiling, so a mistyped date cannot fill the table. */
const MAX_REPEATS = 52;

/**
 * Copies an event forward, one real row a week.
 *
 * This is the whole of the recurrence support, on purpose. Every copy
 * is an ordinary event that can be edited, moved or cancelled on its
 * own, and they share a series id only so they can be found together.
 * Nothing here has to understand "every third Saturday except in
 * December", because nothing here has to: that is just a week somebody
 * deletes.
 */
export async function repeatWeekly(
  id: number,
  weeks: number,
): Promise<{ ok: true; made: number } | { ok: false; error: string }> {
  const n = Math.min(Math.max(Math.round(weeks), 1), MAX_REPEATS);
  const source = await getEvent(id);
  if (!source) return { ok: false, error: "That event is not here any more." };
  const start = asDate(source.startsAt);
  if (!start) return { ok: false, error: "That event has no start date." };

  try {
    await ensureTable();
    const { db } = await import("@/lib/db");
    // The first of a series adopts its own id, so the original is part
    // of the series rather than an odd one out beside it.
    const seriesId = source.seriesId ?? source.id;
    if (source.seriesId === null) {
      await db.execute(
        sql`UPDATE lbs_events SET series_id = ${seriesId} WHERE id = ${id}`,
      );
    }

    const end = asDate(source.endsAt);
    const span = end ? end.getTime() - start.getTime() : null;
    let made = 0;
    for (let w = 1; w <= n; w += 1) {
      const nextStart = new Date(start.getTime());
      nextStart.setDate(nextStart.getDate() + 7 * w);
      const nextEnd = span === null ? null : new Date(nextStart.getTime() + span);
      const slug = await freeSlug(
        slugFor(source.title, nextStart.toISOString()),
        null,
      );
      await db.execute(
        sql`INSERT INTO lbs_events
              (slug, title, summary, body_html, hero_media_id, starts_at,
               ends_at, all_day, venue_name, address, place_slug, business_id,
               category, url, ticket_url, price_text, status, featured,
               source, submitted_email, series_id)
            VALUES (${slug}, ${source.title}, ${source.summary},
                    ${source.bodyHtml}, ${source.heroMediaId}, ${nextStart},
                    ${nextEnd}, ${source.allDay ? 1 : 0}, ${source.venueName},
                    ${source.address}, ${source.placeSlug || null},
                    ${source.businessId}, ${source.category}, ${source.url},
                    ${source.ticketUrl}, ${source.priceText},
                    ${source.status}, 0, ${source.source},
                    ${source.submittedEmail}, ${seriesId})`,
      );
      made += 1;
    }
    return { ok: true, made };
  } catch (e) {
    console.error("[events] repeat failed:", e);
    return { ok: false, error: "Those did not save." };
  }
}

/* ---------- public submission ---------- */

export type SubmissionInput = {
  title: string;
  startsAt: string;
  endsAt: string;
  allDay: boolean;
  venueName: string;
  address: string;
  placeSlug: string;
  category: EventCategory;
  summary: string;
  url: string;
  email: string;
  priceText: string;
  /**
   * A picture, already through the media library.
   *
   * Nothing it is attached to is public until somebody approves it, so
   * an unwanted image is a row in a queue rather than something on the
   * site. The bytes have been re-encoded by then, which is most of why
   * accepting one from a stranger is reasonable at all.
   */
  heroMediaId: number | null;
};

/**
 * Takes an event from the public form.
 *
 * Always pending, never published, whatever the form says. The status
 * is not read from the request at all rather than being validated out
 * of it, because a field that is never accepted cannot be got past by
 * anybody clever with a console.
 */
export async function submitEvent(
  input: SubmissionInput,
): Promise<EventResult> {
  return saveEvent(null, {
    title: input.title,
    summary: input.summary,
    // No body from the public form. Prose from a stranger rendered on
    // our pages is a different question from a line of plain text, and
    // it is not one a submission box needs to open.
    bodyHtml: "",
    heroMediaId: input.heroMediaId,
    startsAt: input.startsAt,
    endsAt: input.endsAt,
    allDay: input.allDay,
    venueName: input.venueName,
    address: input.address,
    placeSlug: input.placeSlug,
    businessId: null,
    category: input.category,
    url: input.url,
    ticketUrl: "",
    priceText: input.priceText,
    status: "pending",
    featured: false,
    source: "submitted",
    submittedEmail: input.email,
  });
}
