#!/usr/bin/env python3
"""H1 audit — find pages with zero or multiple <h1> tags.

Notes:
- header.php wraps the brand wordmark in <h1> globally. Any page that includes
  header.php effectively has at least one h1 from the include. This script flags:
    * zero h1s in the file (relies entirely on header.php — likely missing page h1)
    * 2+ h1s in the file (will render with 3+ once header's brand h1 is added)
- We only scan root-level .php files (the public site). Admin/ is skipped.

Output: markdown to stdout — file path, h1 count, h1 contents, proposed fix.
"""
import os, re, sys, html

ROOT = "/home/cabmansc1/public_html"

RE_H1_OPEN = re.compile(r"<h1\b[^>]*>", re.I)
RE_H1_FULL = re.compile(r"<h1\b[^>]*>(.*?)</h1>", re.I | re.S)
RE_TAG     = re.compile(r"<[^>]+>", re.S)
RE_PHPTAG  = re.compile(r"<\?(?:php)?.*?\?>", re.S)

# Files that aren't user-facing pages (no h1 expected)
SKIP_FILES = {
    "config.php", "Business.php", "User.php",
    "header.php", "footer.php", "nav.php",
    "seo_head.php", "sitemap.php",
    "stripe_config.php", "stripe-webhook.php",
    "pricing_config.php", "pricing_form_section.php",
    "process_business.php", "process_directory_signup.php",
    "process_form.php", "process_login.php",
    "newsletter_subscribe.php", "save-quiz-lead.php",
    "logout.php", "composer-setup.php",
    "admin.php",
}

def clean(s):
    s = RE_PHPTAG.sub("{PHP}", s)
    s = RE_TAG.sub(" ", s)
    return re.sub(r"\s+", " ", html.unescape(s)).strip()

def audit_file(path):
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        src = f.read()
    matches = list(RE_H1_FULL.finditer(src))
    # Also find unclosed <h1 ... > tags (broken markup)
    open_count = len(RE_H1_OPEN.findall(src))
    h1s = []
    for m in matches:
        # Find line number
        line = src.count("\n", 0, m.start()) + 1
        text = clean(m.group(1)) or "[empty]"
        h1s.append((line, text[:140]))
    return open_count, h1s

def gather():
    rows = []
    for entry in sorted(os.listdir(ROOT)):
        full = os.path.join(ROOT, entry)
        if os.path.isfile(full) and entry.endswith(".php") and entry not in SKIP_FILES:
            rows.append((entry, full))
    return rows

if __name__ == "__main__":
    rows = gather()
    print("# H1 Audit — pages with zero or multiple <h1>\n")
    print("Generated by `_seo/_audit_h1.py`. The header.php include wraps the brand wordmark in `<h1>` globally — so the rendered page count is +1 vs what's shown here.\n")
    print("| File | <h1> count in file | First H1 | Status |")
    print("|------|-------------------:|----------|--------|")
    zero = []
    multi = []
    ok = []
    for name, path in rows:
        n, h1s = audit_file(path)
        first = h1s[0][1] if h1s else "—"
        if n == 0:
            status = "**MISSING** — page has no h1; relies entirely on header.php brand h1"
            zero.append(name)
        elif n > 1:
            status = f"**MULTIPLE** — file declares {n} h1s; renders as {n+1} with header.php brand h1"
            multi.append((name, h1s))
        else:
            status = "ok"
            ok.append(name)
        print(f"| `{name}` | {n} | {first[:80]} | {status} |")

    print("\n---\n")
    print(f"## Summary\n\n- {len(ok)} pages with exactly 1 h1 (renders as 2 once header.php h1 counts)")
    print(f"- {len(zero)} pages with 0 h1 (rely on header.php's brand h1 — usually wrong)")
    print(f"- {len(multi)} pages with 2+ h1 in-file (renders as 3+ — definitely wrong)")

    print("\n## Proposed fixes\n")
    print("**Sitewide prerequisite:** demote `header.php`'s brand wordmark from `<h1>` to `<p class=\"brand-wordmark\">`. Until that's done, *every* page renders with at least 2 h1s. Once done, the per-page counts in the table above become the rendered counts.\n")
    if zero:
        print("### Pages with no h1 in the file\n")
        print("Each of these needs an `<h1>` near the top of main content. If migrated to `seo_head.php`, output `<h1><?= $seo['h1'] ?? 'Fallback Title' ?></h1>`. Otherwise insert a literal h1 tied to the page topic.\n")
        for n in zero:
            print(f"- `{n}`")
    if multi:
        print("\n### Pages with multiple h1s in the file\n")
        print("Convert all but the highest-priority h1 to `<h2>`. Listed with line numbers:\n")
        for name, h1s in multi:
            print(f"\n**`{name}`** — keep the first, demote the rest:")
            for line, text in h1s:
                marker = "KEEP" if (line, text) == h1s[0] else "→ <h2>"
                print(f"  - line {line} ({marker}): {text[:100]}")
