#!/usr/bin/env python3
"""Image alt-text audit — find <img> tags missing or empty alt attribute.

Scans root + admin/ PHP and HTML files. Outputs markdown checklist with
file:line, src, and a short context snippet so Andrew can write alt text.
Decorative images that are intentionally alt="" should stay alt="" (they
are listed separately so Andrew can confirm).
"""
import os, re, sys, html

ROOT = "/home/cabmansc1/public_html"
SKIP_DIRS = {"vendor", "_archived", ".trash", "_seo", "node_modules",
             ".well-known", "uploads", "images", "css", "templates"}

# Capture an <img ...> tag (single line OR spanning lines).
RE_IMG = re.compile(r"<img\b[^>]*>", re.I | re.S)
RE_ALT = re.compile(r"\balt\s*=\s*([\"'])(.*?)\1", re.I | re.S)
RE_SRC = re.compile(r"\bsrc\s*=\s*([\"'])(.*?)\1", re.I | re.S)
RE_PHPTAG = re.compile(r"<\?(?:php|=)?.*?\?>", re.S)

# Meta Pixel noscript fallback img — auto-injected per page; one fix in
# seo_head.php (add alt="") covers all of these. Suppress per-page noise.
META_PIXEL_FRAGMENT = "facebook.com/tr?id="

def strip_php_preserve_offsets(s):
    """Replace each PHP block with spaces (and preserve newlines) so that
    subsequent regex matches see clean HTML but line numbers stay correct."""
    def repl(m):
        return "".join(c if c == "\n" else " " for c in m.group(0))
    return RE_PHPTAG.sub(repl, s)

def gather():
    rows = []
    for entry in sorted(os.listdir(ROOT)):
        full = os.path.join(ROOT, entry)
        if os.path.isfile(full) and (entry.endswith(".php") or entry.endswith(".html")):
            rows.append((entry, full))
    for d in sorted(os.listdir(ROOT)):
        full = os.path.join(ROOT, d)
        if os.path.isdir(full) and d not in SKIP_DIRS:
            for entry in sorted(os.listdir(full)):
                fp = os.path.join(full, entry)
                if os.path.isfile(fp) and (entry.endswith(".php") or entry.endswith(".html")):
                    rows.append((f"{d}/{entry}", fp))
    return rows

def audit_file(rel, path):
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        original = f.read()
    # Strip PHP blocks (preserving offsets/line numbers) so the img-tag regex
    # can correctly span PHP echos like `<img src="<?= $x ?>" alt="..." />`.
    src = strip_php_preserve_offsets(original)
    findings_missing = []
    findings_empty   = []
    for m in RE_IMG.finditer(src):
        tag = m.group(0)
        line = src.count("\n", 0, m.start()) + 1
        # Show the ORIGINAL tag (with PHP intact) for the snippet.
        orig_tag = original[m.start():m.end()]
        src_attr_m = RE_SRC.search(orig_tag)
        src_attr = src_attr_m.group(2).strip() if src_attr_m else "(no src attr)"
        # Suppress Meta Pixel noscript img (one global fix needed, not per-page).
        if META_PIXEL_FRAGMENT in src_attr:
            continue
        # Detect alt= presence on the cleaned tag (so the regex can span PHP),
        # but read the ACTUAL alt value from the original tag (so dynamic
        # alt="<?= ... ?>" isn't misclassified as empty).
        alt_present = RE_ALT.search(tag) is not None
        alt_orig_m  = RE_ALT.search(orig_tag) if alt_present else None
        snippet = re.sub(r"\s+", " ", orig_tag).strip()[:200]
        if not alt_present:
            findings_missing.append((line, src_attr, snippet))
        else:
            # Use the original tag's value if we can capture it; otherwise the
            # alt spans a PHP block (e.g. alt="<?= ... ?>") — treat as non-empty.
            alt_val = alt_orig_m.group(2).strip() if alt_orig_m else "<dynamic>"
            if alt_val == "":
                findings_empty.append((line, src_attr, snippet))
    return findings_missing, findings_empty

if __name__ == "__main__":
    rows = gather()
    print("# Missing Image Alt Text — Phase 2 audit\n")
    print("Generated by `_seo/_audit_alt.py`. Two sections:\n")
    print("1. **Missing `alt` attribute entirely** — these will fail accessibility + SEO checks. Andrew needs to write alt text describing what's in each image.")
    print("2. **`alt=\"\"` (empty)** — valid for purely decorative images (icons, spacers, background flourishes). Andrew should confirm each really is decorative; if it conveys meaning, write descriptive alt text.\n")
    print("Dynamic `src` values (PHP echos) still need alt text — write something descriptive based on what the image *role* is, e.g. `alt=\"<?= htmlspecialchars($business['name']) ?> photo\"`.\n")
    print("**Note:** the Meta Pixel `noscript` image (`facebook.com/tr?id=…`) is suppressed from this report. It's auto-injected by `seo_head.php` on every page; one `alt=\"\"` added there fixes all instances at once. Track that as its own one-liner task.\n")

    total_missing = 0
    total_empty   = 0
    files_missing = []
    files_empty   = []

    for rel, path in rows:
        miss, empt = audit_file(rel, path)
        if miss: files_missing.append((rel, miss)); total_missing += len(miss)
        if empt: files_empty.append((rel, empt));   total_empty   += len(empt)

    print(f"---\n\n## 1. Missing `alt` attribute ({total_missing} images across {len(files_missing)} files)\n")
    if not files_missing:
        print("_None — every <img> tag has an alt attribute._\n")
    for rel, items in files_missing:
        print(f"### `{rel}`\n")
        for line, src_attr, snippet in items:
            print(f"- [ ] **line {line}** — `src=\"{src_attr}\"`")
            print(f"  - `{snippet}`")
        print()

    print(f"---\n\n## 2. `alt=\"\"` empty (confirm decorative) — {total_empty} images across {len(files_empty)} files\n")
    if not files_empty:
        print("_None._\n")
    for rel, items in files_empty:
        print(f"### `{rel}`\n")
        for line, src_attr, snippet in items:
            print(f"- [ ] **line {line}** — `src=\"{src_attr}\"` — confirm decorative; if not, add alt text")
        print()
